#!/usr/bin/env python
import sys, os

#IMPORTANT: Please enter your path in the below location
userPath = "C:/Users/Kris/"

preCommitContent = ""
with open(userPath + "PreCommitStorage.txt", "r") as file:
	preCommitContent = file.read()

originalFileLocation = ""
with open(userPath + "hookInfo.txt", "r") as file:
	originalFileLocation = file.read()

with open(userPath + originalFileLocation, "w") as file:
	file.write(preCommitContent)