#!/bin/sh
#grabbing git info in shell, then moving to python for script

#grab a copy of what returns from git diff: In our case the cached "staged docs", then using echo to place the file location in PreCommitStorage.txt
var=$(git diff --name-only --cached)
echo "$var" > PreCommitStorage.txt

#now that we saved the staged filenames, we can run the py script
python C:/Users/Kris/.git/hooks/pre-commit.py

#re-add the file, after changes have happened in script
git add $var